"""Short, mandatory schematic workflow injected into every MCP client."""

from __future__ import annotations

# Keep the protocol first and compact. Small callers reliably follow a short
# sequence and a canonical example; they do not reliably recover priorities
# from a long style guide.
SCHEMATIC = (
    "SCHEMATIC PROTOCOL — FOLLOW IN THIS ORDER:\n"
    "1. PLAN one complete functional block before writing. Query EVERY unique "
    "symbol and unit with `symbol_pins`; choose explicit `(ref, unit, x, y, "
    "rotation, mirror)` entries and reserve visible-field and wire space. For "
    "repeated channels, translate one explicit plan rather than improvising "
    "each copy. Prefer another A4 child sheet over A3.\n"
    "2. PREFLIGHT the complete block with `measure_schematic_placement`. It "
    "does not mutate the sheet. Revise the whole coordinate list until its "
    "overlap and page-violation findings are acceptable.\n"
    "3. PLACE that same list in ONE `add_components` call. Index the returned "
    "parts by `(ref, unit)`. The returned pins are their exact positions ON "
    "THE SHEET after rotation and mirroring; never recompute or guess them.\n"
    "4. WIRE only after placement. Build every explicit straight segment for "
    "the block in memory, then submit them in ONE `add_wires` call. A corner "
    "is two caller-chosen segments. Batch power symbols, labels, flags, "
    "junctions and no-connects once per block as well.\n"
    "5. VERIFY at each completed page: `list_nets`, `check_sheet`, "
    "`check_sheet_layout`, and `render_schematic`. `ok=true` only means a "
    "tool ran; completion requires the relevant `clean=true`, expected net "
    "membership, and a visually inspected render. Recheck after the last "
    "power-symbol, label or field edit: an earlier placement preflight does "
    "not cover later additions. Before PCB work, resolve layout findings or "
    "record an explicit, explained waiver. A render file path alone is not "
    "evidence that its image was reviewed.\n\n"
    "SPATIAL CONTEXT WITHOUT IMAGES:\n"
    "Use `inspect_schematic_scene(path)` for a sheet, or supply x1/y1/x2/y2 "
    "for an explicit region. It returns stable object IDs, parent IDs, bounds, "
    "pin anchors, child-sheet filenames and conservative overlap findings. "
    "Pass its revision as since with the SAME region for changes only; apply "
    "objects/findings by ID and remove the IDs in removed/removed_findings. "
    "Replace your local view when mode=full, including after reset=true. "
    "A parent can lie outside the region; request more context explicitly. "
    "Read only the active block and its needed interfaces rather than the "
    "entire hierarchy. Prefer detail=compact with max_objects=500 and "
    "max_bytes=100000 for local editing. For overlap repair, detail=conflicts "
    "returns findings and only their implicated objects; it omits other "
    "obstacles, so switch back to compact before planning new wires. Keep "
    "the same detail and region for deltas. Geometry does not prove "
    "electrical connections; keep "
    "list_nets and ERC. Text bounds are estimated; the monitor's Geometry "
    "view shows these same bounds, not a pixel-perfect native schematic.\n\n"
    "CANONICAL CALL SHAPE:\n"
    "Create one `parts=[{lib_id, ref, x, y, value, rotation, mirror, unit}, "
    "...]` array. Call `measure_schematic_placement(path, parts)`. If its "
    "findings are acceptable, call `add_components(path, parts)` with that "
    "unchanged array. Build a `(ref, unit)` lookup from the returned `parts`; "
    "find each pin in those replies; create `wires=[{x1, y1, x2, y2}, ...]`; "
    "then call `add_wires(path, wires)` once. Do not hide calls inside a "
    "per-component helper.\n\n"
    "NON-NEGOTIABLE FACTS:\n"
    "* Coordinates are millimetres from the top-left and snap to the 1.27 mm "
    "grid. A wire connects only at the exact pin coordinates returned by the "
    "server.\n"
    "* Every schematic placement, drawing and editing primitive takes a LIST. "
    "A list of one is valid, but do not make one call per item when the whole "
    "block is already known. Placement and wiring remain separate calls.\n"
    "* Send exactly the fields each request model names. A pin reply contains "
    "extra metadata and is not itself a `{x, y}` request; project it to the "
    "required keys. Omit zero-length wire segments. Unknown keys and zero-"
    "length segments are rejected before any write.\n"
    "* Plural writes are atomic: a refused item reports its index and applies "
    "none of the list. Successful writes autosave for live preview; "
    "`save_sheet` additionally validates that KiCad can parse the result.\n"
    "* Use visible wires inside a functional block. Use labels only for "
    "distant, cross-sheet, or otherwise unreadable connections. Use global "
    "labels only for intentionally design-wide signals.\n"
    "* Place GND and +3V3 with `add_power`, then wire to the returned pin. Do "
    "not use labels named GND or +3V3. Use `add_power_flags` only on a point "
    "actually wired to the driven rail.\n"
    "* Add explicit junctions where crossing or T-connected wires must join. "
    "Crossing wires without a junction are separate nets. Mark every "
    "deliberately unused pin with `add_no_connects`.\n"
    "* Set Footprint, Datasheet, MPN and other properties with `set_fields`. "
    "Do not invent a singular `set_field` MCP call.\n\n"
    "HIERARCHY:\n"
    "Batch child boxes with `add_sheets`. Create each child with `new_sheet` "
    "using the exact `instance_path` returned for its box. A parent port and a "
    "child hierarchical label connect by identical name; power symbols and "
    "global labels need no port. Save every child before root-level netlist or "
    "ERC checks, because those checks walk child files.\n\n"
    "EDITING:\n"
    "Use `get_component`, `get_pin`, `list_components`, `list_wires`, and "
    "`list_labels` to read exact current geometry. Move, rotate, mirror or "
    "remove existing objects with their corresponding primitive; never "
    "recreate a sheet merely to repair it. Component edits do not move wires, "
    "so verify connectivity afterwards. A saved sheet reopens automatically "
    "when named by path; `new_sheet` creates and overwrites.\n\n"
)

__all__ = ["SCHEMATIC"]
