"""The schematic half of the server instructions.

Rewritten against the tools that exist. The text this replaces described a
declarative ``apply_design`` document, a floorplanner and a research gate --
none of which are here any more -- and of the 27 schematic tools it named
exactly one. Every tool named below was checked against ``mcp.list_tools()``.

Keep it that way: this file is guidance for a caller, so a name in it that no
tool answers to is the same defect as a broken call.
"""

from __future__ import annotations

#: How to author a sheet with the primitives, and nothing above them.
SCHEMATIC = (
    "Author KiCad 10 schematics from primitives. There is no design document, "
    "no autoplacer and no router: every call does one thing, takes scalars, "
    "and returns what it made. YOU decide where a part goes and where a wire "
    "turns; the server tells you where things ended up.\n\n"

    "DEFAULT SCHEMATIC STYLE -- FOLLOW THIS UNLESS THE DESIGN REQUIRES "
    "OTHERWISE:\n"
    "* Connect nearby components inside one functional block with visible "
    "wires. This is the default connection method.\n"
    "* Connect GND and +3V3 with `add_power`, then wire to the pin returned "
    "for each power symbol. Do not create labels named GND or +3V3.\n"
    "* Use labels only for distant connections, sheet boundaries, or wiring "
    "that would otherwise make the page unreadable. Use a global label only "
    "for a signal intentionally shared across the design.\n\n"

    "PLAN THE PAGE BEFORE PLACING ANY COMPONENT. This is a caller "
    "responsibility, not an automatic server operation. First divide the A4 "
    "page into named functional regions, choose left-to-right signal flow, "
    "reserve explicit wire corridors and power-symbol space, and write down "
    "the intended `(ref, x, y, rotation, unit)` entries for the complete "
    "block. Query `symbol_pins` for EVERY unique symbol and account for its "
    "reported width, height, pin sides, all multi-units, and visible Reference "
    "and Value fields. For a repeated channel, plan one complete channel and "
    "apply an explicit translation; do not improvise each copy. Do not place "
    "one component merely to discover where the next might fit. If the whole "
    "block cannot be pictured with legible signal flow and field space, split "
    "it across A4 child sheets before calling `add_components`. After a block "
    "lands, render and check it before starting the next block; if the plan "
    "fails, revise the block as a whole rather than accumulating local nudges.\n\n"

    "THE ONE THING TO UNDERSTAND: every write takes a LIST, and one item "
    "is a list of one -- there is no singular form to choose between. "
    "`add_components` returns each part's pins at their "
    "positions ON THE SHEET, with rotation and mirroring already applied. Wire "
    "to those numbers. A wire drawn to where a pin would have been if the part "
    "were unrotated looks connected, is not, and nothing on the sheet says so. "
    "`get_component` returns the same pins for a part already placed, and "
    "`get_pin` answers one by number or name.\n\n"

    "Everything is millimetres from the top-left and is snapped to the 1.27 mm "
    "grid. Keep the design in millimetres; do not convert coordinates to mils. "
    "Two points that differ by a fraction of a millimetre are not connected.\n\n"

    "Workflow:\n"
    "1. `find_symbol` matches against `Library:Symbol` ids only -- search by "
    "part number or family (`AP2112`, `USB_C_Receptacle`), not by prose. "
    "`symbol_pins` gives a symbol's pins and size BEFORE placing, which is how "
    "you work out how much room to leave. Finish the functional-region and "
    "coordinate plan described above before step 3.\n"
    "2. `new_sheet` -- use its A4 default. Use A3 only when one indivisible "
    "functional block cannot remain legible on A4 after reasonable layout; "
    "normally split into another A4 child sheet instead. Nothing is on disk "
    "until `save_sheet`.\n"
    "3. `add_components` for the parts; `next_ref` if you would rather not "
    "keep a counter. `rotation` must be 0, 90, 180 or 270 -- any other angle writes "
    "a file KiCad refuses to open, and the call will not stop you. `mirror` is "
    "'x', 'y' or empty. A multi-unit symbol (an LM358 is two op-amps plus a "
    "shared power unit) is placed ONE UNIT PER ENTRY, all units sharing one "
    "ref; keep the pins the reply carried, because `get_pin`, `set_fields`, "
    "`move_fields` and `get_fields` only ever see unit 1.\n"
    "4. Wire it: use direct wires between nearby components in the same "
    "functional block. `add_wires` draws straight segments, so a corner is two "
    "of them. `add_junctions` where a wire T's or crosses another it "
    "must join -- wires that cross without one are NOT connected. "
    "Use labels for distant connections, crossings that would make the page "
    "unreadable, and sheet boundaries -- not as a substitute for every local "
    "wire. `add_labels` names nets: "
    "two labels with the same text are one net with no wire between them.\n"
    "5. `add_power` for the rails (especially GND and +3V3) -- each returns a "
    "single pin, which is what you wire to. Use one symbol per readable local "
    "power cluster, and add another rather than drawing a long rail across the "
    "page. Power symbols replace GND/+3V3 labels; they do not replace the short "
    "visible wires from component pins. `add_power_flags` "
    "on each supply, wired at a point that is actually on that net; a flag "
    "placed nearby but not touching is unconnected and drives nothing. "
    "Otherwise ERC reports the rail as undriven. "
    "`add_no_connects` on pins left unconnected on purpose.\n"
    "6. `set_field(ref, 'Footprint', ...)` is how a part gets a footprint. "
    "There is no separate call: a footprint is a field with a name the board "
    "export happens to read. `Value`, `Datasheet`, `MPN` work the same way.\n"
    "7. `save_sheet`, then CHECK -- see below.\n\n"

    "Checking, and do not skip it: `list_nets` is the only call that tells you "
    "what the sheet ACTUALLY connects, read back from KiCad itself rather than "
    "from what you believe you drew. A schematic can be a valid file that "
    "opens and renders correctly while its wires join nothing. `check_sheet` "
    "runs ERC and names each violation by part and pin. Its `ok=true` means "
    "the check executed; only `clean=true` means it found nothing. The same "
    "distinction applies to `check_sheet_layout`. Treat `clean=false` as "
    "unfinished unless the caller records an explicit warning waiver. "
    "`what_is_at` answers "
    "the same question one point at a time -- is this actually connected? -- "
    "and is what to reach for when a net came out wrong.\n\n"

    "BEFORE COMPLETION: call `list_labels` and replace any convenience label "
    "named GND or +3V3 with an `add_power` symbol and visible wire. Confirm "
    "nearby parts are wired rather than joined by local labels. Then use "
    "`list_nets`, `check_sheet`, `check_sheet_layout`, and "
    "`render_schematic`; connectivity, ERC, likely collisions, and visual "
    "readability are four separate checks.\n\n"

    "Then LOOK AT IT. `check_sheet_layout` reports likely intersections: "
    "fields, labels and notes crossed by wires, and visible text overlapping "
    "other visible text. It does not move anything. "
    "`render_schematic` writes a PNG per page and remains necessary because "
    "geometry cannot judge poor signal flow, crowding, or confusing wire "
    "paths. It saves the sheet first, so the picture is of what you drew "
    "rather than what was last written.\n\n"

    "REACH FOR A SECOND A4 SHEET EARLY. A3 is a last resort for one block that "
    "cannot be divided without making its signal flow harder to understand. A "
    "page crammed to its border is one nobody can read even when ERC calls "
    "it perfect. A sheet costs one `add_sheets` call and one `new_sheet`, "
    "and it buys a design someone can follow: one page per FUNCTION -- "
    "power, MCU, sensors, IO -- rather than one page per available square "
    "millimetre. Split when a block stops being about one thing, not when "
    "you run out of room.\n"
    "* `add_sheets` puts child boxes on the root and returns where each "
    "one's ports landed, and an `instance_path` per box.\n"
    "* Create the child with `new_sheet`, PASSING THAT `instance_path`. Get it "
    "wrong and the child's parts annotate against the wrong sheet, their nets "
    "never merge into the design, and nothing says so.\n"
    "* Signals cross by NAME: a port on the box, and `add_labels` with "
    "`kind='hierarchical'` and the SAME name inside the child. Nothing checks "
    "the pairing while you draw.\n"
    "* Power does not need ports. `kind='global'` labels and power symbols "
    "join across the whole design wherever they are.\n"
    "* `save_sheet` EVERY child before `list_nets` or `check_sheet` on the "
    "root. Those two read children from disk, so an unsaved child is reported "
    "as though its parts were not there, with no warning.\n\n"

    "`add_texts` writes a NOTE -- plain text that connects nothing and "
    "ERC never sees. It is not `add_labels`, which looks the same on the "
    "page and is the thing that JOINS. Notes are for what a reader needs "
    "and the netlist must not have: a revision block, why a resistor is "
    "13k7, all VBAT caps 50 V. The board has `add_board_texts`; this is "
    "the schematic's.\n\n"

    "Local labels: do not normally place one directly on a component pin. Draw "
    "a short wire stub away from the body and put the local label at its free "
    "end; otherwise its text begins at the pin and can grow across the symbol, "
    "pin number or value. Set `justify` explicitly: use 'right' on a left-side "
    "pin so the text grows left, and 'left' on a right-side pin so it grows "
    "right. The default cannot infer which side of a component the caller "
    "intended. Local labels can be rotated with `rotate_labels`, using their "
    "uuid from `add_labels` or `list_labels`; use 90 or 270 for vertical text. "
    "A horizontal local label renders identically at 0 and 180. Global and "
    "hierarchical labels retain their normal flag/justification behavior.\n\n"

    "Conventions worth following: signal flows left to right; power symbols "
    "point up and grounds down; wire components directly inside a functional "
    "block and use labels only for long or cross-block connections; a "
    "decoupling cap sits 2.54-5 mm from the "
    "pin it serves. None of this is enforced -- it is what makes a sheet "
    "readable, and only you can see the sheet.\n\n"

    "Reference and Value are placed automatically, clear of the side the "
    "part's wires leave from. That is a default, not a rule: on a crowded "
    "sheet two parts' labels can still meet, and `move_fields` is how one gives "
    "way. `list_components`, `list_wires` and `get_fields` read back what is "
    "there.\n\n"

    "Everything else on a sheet can be changed too. Labels carry a stable "
    "uuid from `add_labels` or `list_labels`; use it after moving or mirroring "
    "nearby parts. Wires, junctions and no-connects are addressed by where "
    "they are: "
    "`move_wires`, `remove_wires`, `move_labels`, `rotate_labels`, "
    "`remove_labels`, `remove_junctions`, `remove_no_connects`, "
    "`move_sheets`, `remove_sheets`, `remove_fields`. Pass the "
    "coordinates this server REPORTED -- from `list_wires`, or from the "
    "reply that drew the thing -- because they are snapped and one you "
    "worked out yourself may miss. Each says how many it FOUND, so "
    "nothing quietly does nothing. `move_sheets` keeps the box uuid and "
    "its instance_path, so a page moves without rebuilding its "
    "children.\n\n"

    "To change parts after placing them: `move_components`, "
    "`rotate_components`, `mirror_components`, `remove_components`. Each "
    "returns the parts with their pins where they NOW are, which is the "
    "reason to use one rather than removing and re-placing. They do not "
    "move the wires you already drew. `move_components` also takes "
    "`refs` with `dx`/`dy` to SHIFT a set: choose the set yourself with "
    "`list_components` and filter it, because nothing here infers which "
    "parts you meant.\n\n"

    "A SAVED SHEET REOPENS BY ITSELF. Name an existing file in any call and "
    "it is read from disk -- there is no open call and you do not need one. "
    "`new_sheet` CREATES, and overwrites whatever was there, so do not "
    "reach for it to get back to a design you already have.\n\n"
    "A sheet stays open in the server between calls, keyed by its path, so a "
    "session is a sequence of small calls rather than a re-parse each time. "
    "Work in batches -- every call is a full round-trip -- and check at "
    "milestones rather than after every wire.\n\n"
)

__all__ = ["SCHEMATIC"]
